# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: dr1234
      MYSQL_USER: root
      MYSQL_PASSWORD: lp1234
      DATABASE_HOST: 127.0.0.1

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
